# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dchud_wrap <- function(r, ldr, p, x, z, ldz, nz, y, rho, c, s) {
    invisible(.Call(`_rollRegres_dchud_wrap`, r, ldr, p, x, z, ldz, nz, y, rho, c, s))
}

dchdd_wrap <- function(r, ldr, p, x, z, ldz, nz, y, rho, c, s, info) {
    invisible(.Call(`_rollRegres_dchdd_wrap`, r, ldr, p, x, z, ldz, nz, y, rho, c, s, info))
}

#' @import Rcpp
#' @useDynLib rollRegres, .registration = TRUE
roll_cpp <- function(X, Y, window, do_compute_R_sqs, do_compute_sigmas, do_1_step_forecasts, grp, use_grp, do_downdates, use_min_obs = FALSE, min_obs = 0L) {
    .Call(`_rollRegres_roll_cpp`, X, Y, window, do_compute_R_sqs, do_compute_sigmas, do_1_step_forecasts, grp, use_grp, do_downdates, use_min_obs, min_obs)
}

.find_chunks <- function(grp, width, min_obs) {
    .Call(`_rollRegres_chunk`, grp, width, min_obs)
}

