# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @import Rcpp
#' @useDynLib rollRegres, .registration = TRUE
roll_cpp <- function(X, Y, window, do_compute_R_sqs, do_compute_sigmas, do_1_step_forecasts) {
    .Call(`_rollRegres_roll_cpp`, X, Y, window, do_compute_R_sqs, do_compute_sigmas, do_1_step_forecasts)
}

